name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      CSRF_SECRET_KEY: "12323"  # Placeholder key

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: npm install bitcore-node@3.1.3 bufferutil@1.2.1 utf-8-validate@1.2.2 zmq@2.15.3

      - name: Build step
        run: deno task build

      # - name: Start Deno app
      #   run: deno run -A dev.ts &
      #   env:
      #     PORT: 8000

      # - name: Wait for Deno app to be ready
      #   run: |
      #     echo "Waiting for Deno app to start..."
      #     sleep 10

      # - name: Install Dredd
      #   run: npm install -g dredd

      # - name: Run Dredd tests
      #   run: dredd
      #   env:
      #     DREDD_SERVER: http://localhost:8000